### Random numbers

In [5]:
import random

In [6]:
# random float in [0,1)
a = random.random()
print(a)

# random float in range [a,b]
a = random.uniform(1,10)
print(a)

# random integer in range [a,b]. b is included
a = random.randint(1,10)
print(a)

# random integer in range [a,b). b is excluded
a = random.randrange(1,10)
print(a)



0.19968341600413386
4.963255742183849
10
4


In [7]:
# random float from a normal distribution with mu and sigma
a = random.normalvariate(0, 1)
print(a)

# choose a random element from a sequence
a = random.choice(list("ABCDEFGHI"))
print(a)

# choose k unique random elements from a sequence
a = random.sample(list("ABCDEFGHI"), 3)
print(a)

# choose k elements with replacement, and return k sized list
a = random.choices(list("ABCDEFGHI"),k=3)
print(a)

# shuffle list in place
a = list("ABCDEFGHI")
random.shuffle(a)
print(a)

0.22717549293982817
I
['D', 'E', 'G']
['B', 'I', 'A']
['G', 'C', 'A', 'F', 'D', 'B', 'I', 'E', 'H']


## The seed generator
With random.seed(), you can make results reproducible, and the chain of calls after random.seed() will produce the same trail of data. The sequence of random numbers becomes deterministic, or completely determined by the seed value.

In [8]:
print('Seeding with 1...\n')

random.seed(1)
print(random.random())
print(random.uniform(1,10))
print(random.choice(list("ABCDEFGHI")))

print('\nRe-seeding with 42...\n')
random.seed(42)  # Re-seed

print(random.random())
print(random.uniform(1,10))
print(random.choice(list("ABCDEFGHI")))

print('\nRe-seeding with 1...\n')
random.seed(1)  # Re-seed

print(random.random())
print(random.uniform(1,10))
print(random.choice(list("ABCDEFGHI")))

print('\nRe-seeding with 42...\n')
random.seed(42)  # Re-seed

print(random.random())
print(random.uniform(1,10))
print(random.choice(list("ABCDEFGHI")))

Seeding with 1...

0.13436424411240122
8.626903632435095
B

Re-seeding with 42...

0.6394267984578837
1.2250967970040025
E

Re-seeding with 1...

0.13436424411240122
8.626903632435095
B

Re-seeding with 42...

0.6394267984578837
1.2250967970040025
E


## Random numbers with NumPy

In [9]:
import numpy as np 

In [10]:
values = np.random.randint(0, 10, (5,3))
print(values)

[[0 4 1]
 [8 5 0]
 [9 8 9]
 [0 3 1]
 [7 4 5]]


In [11]:
values = np.random.randn(5)
print(values)

[ 1.21379717  0.12690162  0.97107372 -0.08927011 -0.25385078]


In [12]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
np.random.shuffle(arr)
print(arr)

[[4 5 6]
 [1 2 3]
 [7 8 9]]
